#For build testing using Travis-ci
language: android
dist: trusty
android:
  components:
  # The BuildTools version used by your project
  - build-tools-30.0.0
  
  # The SDK version used to compile your project
  - android-22
  - extra
  - tools
  - platform-tools
  
  # Emulator env
  - sys-img-armeabi-v7a-android-22
  #gradlew exec-perm 
before_install:
 - chmod +x gradlew
 - export ANDROID_HOME=~/android-sdk-linux
 - wget -q "https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip" -O android-sdk-tools.zip
 - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
 - rm android-sdk-tools.zip
 - PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
 - mkdir -p ~/.android
 - touch ~/.android/repositories.cfg
 - echo yes | ./sdkmanager "platforms;android-22"
 - echo yes | ./sdkmanager "platforms;android-30"
 - echo yes | ./sdkmanager "build-tools;30.0.0"
 - echo yes | ./sdkmanager --licenses

# Emulator Management: Create, Start and Wait
before_script:
  - android list targets # list pre-installed targets # <---- list all installed targets
  - echo no | android create avd --force --name test --target android-22 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
